import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";

function csvCell(value: unknown): string {
  const s = String(value ?? "");
  return /[",\n]/.test(s) ? `"${s.replaceAll('"', '""')}"` : s;
}

export async function GET(
  _request: Request,
  { params }: { params: Promise<{ id: string; type: string }> }
) {
  const { id, type } = await params;
  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  // RLS restricts this query to jobs in the caller's organizations.
  const { data: job } = await supabase
    .from("jobs")
    .select("id, product_type, status, created_at, delivered_at, solicitations(title, buyer, solicitation_number)")
    .eq("id", id)
    .maybeSingle();
  if (!job) return NextResponse.json({ error: "Not found" }, { status: 404 });

  if (type === "compliance") {
    const { data: rows } = await supabase
      .from("requirements")
      .select("*")
      .eq("job_id", id)
      .order("requirement_code");
    const header = [
      "requirement_code",
      "requirement_text",
      "source_page",
      "source_section",
      "mandatory",
      "evaluation_weight",
      "planned_response_section",
      "evidence_status",
      "risk_level",
    ];
    const csv = [
      header.join(","),
      ...(rows ?? []).map((r) =>
        header.map((h) => csvCell((r as Record<string, unknown>)[h])).join(",")
      ),
    ].join("\n");
    return new NextResponse(csv, {
      headers: {
        "Content-Type": "text/csv",
        "Content-Disposition": `attachment; filename="bidpilot-compliance-matrix-${id.slice(0, 8)}.csv"`,
      },
    });
  }

  if (type === "draft") {
    const { data: sections } = await supabase
      .from("draft_sections")
      .select("section_name, content_markdown, version, created_at")
      .eq("job_id", id)
      .order("created_at", { ascending: true });
    const sol = job.solicitations as unknown as { title: string | null; buyer: string | null } | null;
    const md = [
      `# Proposal First Draft`,
      ``,
      `**Solicitation:** ${sol?.title ?? "N/A"}`,
      `**Buyer:** ${sol?.buyer ?? "N/A"}`,
      `**Generated by BidPilot:** ${new Date().toISOString()}`,
      ``,
      `> Material claims cite approved evidence IDs inline as [EV:id].`,
      `> [CUSTOMER CONFIRMATION REQUIRED] placeholders mark facts you must confirm before submission.`,
      ``,
      ...(sections ?? []).flatMap((s) => [`## ${s.section_name}`, ``, s.content_markdown, ``]),
    ].join("\n");
    return new NextResponse(md, {
      headers: {
        "Content-Type": "text/markdown",
        "Content-Disposition": `attachment; filename="bidpilot-draft-${id.slice(0, 8)}.md"`,
      },
    });
  }

  if (type === "audit") {
    const [{ data: runs }, { data: decisions }, { data: reviews }] = await Promise.all([
      supabase
        .from("agent_runs")
        .select("agent_name, model_name, prompt_version, status, is_mocked, confidence, token_input, token_output, estimated_cost_cents, duration_ms, gemini_response_id, created_at")
        .eq("job_id", id)
        .order("created_at", { ascending: true }),
      supabase.from("bid_decisions").select("*").eq("job_id", id),
      supabase.from("human_reviews").select("review_type, decision, notes, minutes_spent, created_at").eq("job_id", id),
    ]);
    const audit = {
      job: {
        id: job.id,
        product_type: job.product_type,
        status: job.status,
        created_at: job.created_at,
        delivered_at: job.delivered_at,
      },
      agent_runs: runs ?? [],
      bid_decisions: decisions ?? [],
      human_reviews: reviews ?? [],
      generated_at: new Date().toISOString(),
    };
    return new NextResponse(JSON.stringify(audit, null, 2), {
      headers: {
        "Content-Type": "application/json",
        "Content-Disposition": `attachment; filename="bidpilot-audit-${id.slice(0, 8)}.json"`,
      },
    });
  }

  return NextResponse.json({ error: "Unknown export type" }, { status: 400 });
}
